{% set version = '3.1-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-grpreg
  version: {{ version|replace("-", "_") }}

source:
  fn: grpreg_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/grpreg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/grpreg/grpreg_{{ version }}.tar.gz
  sha256: 47cb1b45761dd5c82fd0ee49a21c16046db4da6c1e8e91fc52436dea25ecaf44

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: grpregOverlap, knitr, survival
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-matrix

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('grpreg')"           # [not win]
    - "\"%R%\" -e \"library('grpreg')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=grpreg
  license: GPL-3
  summary: Efficient algorithms for fitting the regularization path of linear or logistic regression
    models with grouped penalties.  This includes group selection methods such as group
    lasso, group MCP, and group SCAD as well as bi-level selection methods such as the
    group exponential lasso, the composite MCP, and the group bridge.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: grpreg
# Title: Regularization Paths for Regression Models with Grouped Covariates
# Version: 3.1-3
# Date: 2018-04-07
# Author: Patrick Breheny [aut, cre], Yaohui Zeng [ctb]
# Maintainer: Patrick Breheny <patrick-breheny@uiowa.edu>
# Depends: R (>= 3.1.0), Matrix
# Suggests: grpregOverlap, knitr, survival
# VignetteBuilder: knitr
# Description: Efficient algorithms for fitting the regularization path of linear or logistic regression models with grouped penalties.  This includes group selection methods such as group lasso, group MCP, and group SCAD as well as bi-level selection methods such as the group exponential lasso, the composite MCP, and the group bridge.
# BugReports: http://github.com/pbreheny/grpreg/issues
# License: GPL-3
# NeedsCompilation: yes
# Packaged: 2018-04-07 12:38:47 UTC; pbreheny
# Repository: CRAN
# Date/Publication: 2018-04-08 11:13:01 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
