travis:
  secure:
    BINSTAR_TOKEN: tz2P68QHpm6R/LUcune9AhZ0xA1hZvgiYUl8/632xU2+m30zzpFvTvCzLNkAB5tEBoGxoFq8ut4LWa56++q6CknxlNwvJD56r3Yit/fJS4mMiCmgUFVfFRadwsKIuQcD4d3jggm1iCryzQFEuUE1kl92h8LJmk4Z4ra2pBPeASPsmvDFGrWGwAftWssdnFa4PzcDPzBUqAhQzIO/TsIxPp3i46LUUTkMJ11taXr+c2xAMG1+szMqfoJfMZ6u6HtotHtfFncr8rOwKRLitWr5anuRdregdIE/AZLPbOWjpduUztz2Z61V2KJ3F9AQr9VrQv/mCogXVJigSPpisvy8c9b7tg4YuHlbjR2zJObeHLho5+bjv0FAn5BDKxa50JSwBRqZGw+0XIGWZM1P7J2/JkxktwkFIoss+BJ7DnL2g+2jpjNz3IhYM6+M4HFVcU2+eOzTw9DiyL/RYHiMMPSLYba5WfX2JKThqhlrYCGoGHOc73Utu5DUCuE9OYbGdUQq9MnWZfCmTPqx05mNP60Ezu/S6B0wy8OjCeVUqh40hcSpotjFQw5ayIulkfT5zbZwtJDDaEQgk3vislE/Ym8y6fOd7gUbVaKhOsqchfRoB3XUa82l3sxhwZRZBhMN/LMmb5DOmqeCp4IQzwwHT439d+6SLMJJ9rHmVYAD5ajvuuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
