travis:
  secure:
    BINSTAR_TOKEN: RCNyFao7ogEVTXM/7QnWtbumQNqlNO1WZoNX4aOq+gtNccfeSLBHePucBKzbmyX16GGH7ekpAIF/1/Oe6gc65yiZTQ10CdkHENSnkNObT++lZEj86CwValzIH55+84UsvtGnXB8fs0RWVnIiByJoK9QGkHpfXcmo7cO7ZqFz4i0BxjqPb+3bXIO8izfMnkynv3mkuOT91spbCG3Pk1z/cSziy1CTAGwv/WN5OC1e189RWJPuyj9sR3QkzRRUnRUfWLqvUBWwrVzs9yfx5v713gjIxMfw9+suPuultgDO35RP4pSX1vPPmZMbsyyPL0ew52aQFnu4dvgJ+V7rh6Pi/kJy8PbzQ86cO50XYQD71P3dFbC7r74XxY+Mtbgffg6JxcOiVJYOAzue1iXRU4tJ19gmnCxzmEkxxvF1LImbkhO+RPJPNDz479mcfvsReo+a4WPETheC4nTSmrNLcpYq5Lxghm2TAgeSZG2pbmpGtjZEFwMbtcEV+Ai9FBGxsAPwaZnbPFvTv48Nd/wleEO/Ht+CTXwror+p/T21cl0oPmghOutZcMqpv/aE7COUJjSRe3Fgyf7gVuC1TliOcpbef54BSrY4vMjnUkfMErYJrgvIPhePDnZhfn2W7sdFPZ5hWdFgfdb1Q18PPVfxsSjouhG/IPO6nmL3f7FUku0v4Ik=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
