travis:
  secure:
    BINSTAR_TOKEN: g3+8RVkfvkEImtezGlHpVg6kGPuDySEgezOgEafC8aD9PitLoreab+uZEZVzEreE/x1Rtm+neGrLR91SdfoVBpZKk0tobB7kZu1fU9fl/qGOcbvJmEQPnmIGwmcuT/sUPhci4Z4NY3q3lVAfzuouYl8d7o8E8dSoRSsfiBIv/ToyjOqDG209ewGkxnCIUmJa4c7A+T3xQqMXSh0y4ar3D7+yUNm4LJhHkD/B+XXW61F/CMUAAWkzuEqTBJ9i8ao5OekDmeZZz4iCR6sM1E1WVgQck5eVFwyarnmqJHYp2eALC2hlIZRKKlLwv4rgrYzgGmnx6/oAod3AHf6bhPxZ5gyBfH+xNESyaCnxSA2b1kAUlB89olNo6FGnzHilWpp3gLnQMrysBQY0hggfrwZRPCm+3h8t9OhMLNhjLEvrX3lP8H5BVBVWbCQM1X+J8WOqSemvUsgZiqP9XniswdP5A88kigf/xM7HoYbb5QgXXnSfdYSSloR1HBXVHTMMFQsPlRmwgpLdv7BZPKGAwbA0w+wpeB05PB2Lo3QWml45diaTv2T64TnxRfW8vYrXJvcOA3qokjpAZIpnWKw1LnApJj4iDyo/EzhrEkCKgDGcCzneE6IlYbfhQySsGS8RxrXxE3NnZcKynB23xo7mnVmZSLBw07XO5SBpdz9lMrEBgZw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
