travis:
  secure:
    BINSTAR_TOKEN: wMPlGSLyvAXc4/wUoAKDP1BfBbNmjsAO/1/DnzspsXubGVmEqrPfKd6sMg9ArIFLb7hfkM0ZOUNb5kq1+YU64pcHEo5xzcjGgHA15XKTEXKgYTQaiULSJeziZ+pCMVDOCEpXL3tAt+xpfRVB/IvqxKKvZ14+ha+iDEtE0GoHWlGcZYo19ty8BOCnEb6lzZFvAbbQKo0xxE/+TuiG+3FwKtx7QNUscY1IFUwuQSK8o8m9+AnSu28cQYGWqsSiarpkarF/P/eeLtRnuFV3oIJbEl77ioBl6oe7/TUhopLEjEp8QaNqnHLv4KRDDwu9mazbl4xwevSpNyUqqJ4o6P0V7zGvGIXAFZxhguXoLyxZCxWPyhMRWNOKpDxc40C8WQ1hnfbdTClynwaL54knfTnSk5Ggv5kwUKAkRA1uRw0CPFe1kUNlAYVt30zbxp4M+aImvrmf4DbSxqrPP/gvr+ExFag2hebB8w5YInVI+8KpXwb4ZxkkuH6ZTCHRH0/E4z7ImSsjtRuWuJq/6aSQPtNqdjYMG83rd0hJluImJHCoPFIKZPIKdWCbDcB3mbnILJFaipa8A903SjDuOUVX836QYsmgnCuLbTTEk+5NWqwhGnxuNCX23829cgTiE1Kazp+y6BIYrj21tCatIxnxmkCmOgMkoBpr6SLzO2eWb9z9cOU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
