travis:
  secure:
    BINSTAR_TOKEN: lW/oPIpKAaf74ZqSGEuuRP1UWCDAgXBvBpKdlfRadvxy5ROfYVXKbc04YHo6RVsO5PRGhvGxZiFIb461RHskJLp6fvTTCqApQGHC0kz/QMYYNCAF950zwG7NSbHDsi9YmyPaGNE97zImurAHnryykuxhobPoLXe3DTLw6oPfuOvl1j6ED3INxf0SRX80fYQuk5PjlOxUviAH1or0rIy2oQJddthtfeAGoEUPujw1z0NiGLf1C6mzSmc8qxHlskf7++IWNm8LPvcfJhkxCaFE99NL0vRRDeRSqY//RbHAaywIWKACe1WXSbmcfx0LpLstKLnn67FhzRVITrLsKls2z/VYGayL1UHoFj48uLMnmE4egK5s55xJOusK8DJmxxkB1CSdMhrOC5TMbEUi+I41soUi6XQNx7+B8TOQQY9DNN4aUqmjVGIrpMUVZMGO5oGweUhXL+f1MENvIoxST/AzknLpuzmvsEHL0k8oZVF4TKOvToMFsO6oS8gfCCxxCJy5pvsOCZ/tGQU5tE+lUlX8mXS9OG7aY7hTI7+J4KZSVkbyEf3chL3GRbq47y+wkhhWlcDL3nyPFZ1l/hGEGr16QMHGqMNzBvdAyCPVBIDMQfefYBb0QXDA80NMwDGDpWKvvQkKVpR2DgkI+X25KjL7ei/OOX+3Xo6tLfYq4IxR724=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
